---
title: "R-Einführung"
author: "Eugene Harschack"
date: "16 Juli 2017"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r mtcars}
class(mtcars)
dim(mtcars)
str(mtcars)
head(mtcars)
summary(mtcars)
colnames(mtcars)
```



```{r mtcars_plots}
library(dplyr)
 mtcars$names<-rownames(mtcars)

 barplot(mtcars$mpg)
 text(mtcars$mpg,mtcars$hp,rownames(mtcars))
 
 mtc<-arrange(mtcars, mpg)
 mids<-barplot(mtc$mpg)
 text(mids,mtc$mpg, round(mtc$mpg), pos = 3, cex=0.8)
 axis(side=1, at=mids, labels=mtc$names, las=2)
 
 mtc<-arrange(mtcars, hp)
 mids<-barplot(mtc$hp)
 text(mids,mtc$hp, round(mtc$hp), pos = 3, cex=0.8)
 axis(side=1, at=mids, labels=mtc$names, las=2)
 
mtcars$lphkm<-(100*3.785411784) / (1.609344*mtcars$mpg)
  
plot(mtcars$hp,mtcars$lphkm)
mod<-lm(data=mtcars, formula= lphkm~hp)

x=min(mtcars$hp):max(mtcars$hp)
y=mod$coefficients[1]+mod$coefficients[2]*x

lines(x,y, col="red")

plot(mtcars$hp,mtcars$lphkm, pch=20, col="grey70")
lines(x,y, col="red")
text(mtcars$hp, mtcars$lphkm, mtcars$names, cex=0.7, pos=3)
  
plot(mtcars$hp,mtcars$lphkm, pch=20, col="grey70", 
     xlim=c(min(mtcars$hp)*0.9, max(mtcars$hp)*1.1),
     ylim=c(min(mtcars$lphkm)*0.9, max(mtcars$lphkm)*1.1))
lines(x,y, col="red")
text(mtcars$hp, mtcars$lphkm, mtcars$names, cex=0.7, pos=3)

```


